---
title: "Final (option 2)"
author: "Matti Harrison"
date: "11/3/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidytext)
library(janitor)
library(leaflet)
library(ggmap)
library(zipcode)
library(maps)
library(viridis)
library(ggthemes)
```

```{r, echo=FALSE, warning= FALSE, error= FALSE, message= FALSE}
la <- read_csv("2010_Census_Populations_by_Zip_Code.csv")

connecticut <- read_csv("2010_Census_Population_And_Housing_Units_By_Town.csv")
```

```{r, echo=FALSE, warning= FALSE, error= FALSE, message= FALSE}
la_clean <- la %>% 
  clean_names() %>% 
  filter(total_population > 0) %>% 
  write_rds(path = "zipcode_data")
```

```{r, echo=FALSE, warning= FALSE, error= FALSE, message= FALSE}
head(la_clean)
```

```{r, echo=FALSE, warning= FALSE, error= FALSE, message= FALSE}
la_clean %>% 
  ggplot(aes(x = total_population, y = average_household_size, color = median_age)) + geom_point() + labs(title = "Population in LA and Average Household Size, using zipcode data", subtitle = "As people get older they have a smaller household size", x = "Population per Zipcode", y = "Average Household Size", color = "Median Age per Zipode")
```

```{r, echo=FALSE, warning= FALSE, error= FALSE, message= FALSE}
leaflet(options = 
            leafletOptions(dragging = FALSE,
                           minZoom = 6, 
                           maxZoom = 12))  %>% 
     addProviderTiles("CartoDB")  %>% 
     setView(lng = -118.2437, lat = 34.0522, zoom = 9)
```